<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/SolSharp.Core/SolSharp.Core.csproj" />
    <ProjectReference Include="../../src/SolSharp.Wallet/SolSharp.Wallet.csproj" />
    <ProjectReference Include="../../src/SolSharp.Rpc/SolSharp.Rpc.csproj" />
    <ProjectReference Include="../../src/SolSharp.Programs/SolSharp.Programs.csproj" />
  </ItemGroup>

</Project>
